# Generated by Django 5.2.1 on 2025-05-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(help_text='In grams or unit count')),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('bulking', 'Bulking'), ('cutting', 'Cutting')], max_length=20)),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non-Vegetarian'), ('ovo-vegetarian', 'Ovo-Vegetarian')], max_length=20)),
                ('calories', models.PositiveIntegerField()),
                ('ingredients', models.ManyToManyField(to='plan_logic.ingredientmodel')),
            ],
        ),
    ]
